# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mysql.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(494, 588)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.frame_31 = QtWidgets.QFrame(Dialog)
        self.frame_31.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_31.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_31.setObjectName("frame_31")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_31)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 2)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.frame = QtWidgets.QFrame(self.frame_31)
        self.frame.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frame.setStyleSheet("QFrame {\n"
"    background-color:rgb(232, 232, 232);\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(18, 0, 18, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel {\n"
"    width:10px\n"
"}")
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.connection_name = QtWidgets.QPushButton(self.frame)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.connection_name.setFont(font)
        self.connection_name.setStyleSheet("QPushButton {\n"
"    text-align:right;\n"
"}")
        self.connection_name.setFlat(True)
        self.connection_name.setObjectName("connection_name")
        self.horizontalLayout.addWidget(self.connection_name)
        self.verticalLayout_11.addWidget(self.frame)
        self.frame_5 = QtWidgets.QFrame(self.frame_31)
        self.frame_5.setMaximumSize(QtCore.QSize(16777215, 60))
        self.frame_5.setStyleSheet("QFrame {\n"
"    background-color:rgb(232, 232, 232);\n"
"}")
        self.frame_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_2.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_3 = QtWidgets.QFrame(self.frame_5)
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frame_3.setStyleSheet("QFrame {\n"
"    background-color:rgb(232, 232, 232);\n"
"}")
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_3.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.frame_3)
        self.label_3.setStyleSheet("QFrame {\n"
"    background-color:rgb(232, 232, 232);\n"
"}")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        spacerItem1 = QtWidgets.QSpacerItem(375, 8, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout_2.addWidget(self.frame_3)
        self.frame_12 = QtWidgets.QFrame(self.frame_5)
        self.frame_12.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frame_12.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.frame_12)
        self.horizontalLayout_13.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.connection_type = QtWidgets.QComboBox(self.frame_12)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.connection_type.setFont(font)
        self.connection_type.setStyleSheet("QComboBox {\n"
"    border-radius:4px;\n"
"    background-color:rgb(232, 232, 232);\n"
"    border:1px solid rgb(132, 132, 132);\n"
"    padding:5px;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    padding:6px;\n"
"    color: rgb(95, 95, 95);\n"
"    border:1px solid  rgb(159, 159, 159);\n"
"}")
        self.connection_type.setObjectName("connection_type")
        self.connection_type.addItem("")
        self.horizontalLayout_13.addWidget(self.connection_type)
        self.verticalLayout_2.addWidget(self.frame_12)
        self.verticalLayout_11.addWidget(self.frame_5)
        self.frame_10 = QtWidgets.QFrame(self.frame_31)
        self.frame_10.setMaximumSize(QtCore.QSize(16777215, 60))
        self.frame_10.setStyleSheet("QFrame {\n"
"    background-color:rgb(232, 232, 232);\n"
"}")
        self.frame_10.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_10)
        self.verticalLayout_3.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_4 = QtWidgets.QFrame(self.frame_10)
        self.frame_4.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.frame_4.setFont(font)
        self.frame_4.setStyleSheet("QFrame {\n"
"    background-color:rgb(232, 232, 232);\n"
"}")
        self.frame_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_4.setContentsMargins(9, 0, 116, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("QFrame {\n"
"    background-color:rgb(232, 232, 232);\n"
"}")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        spacerItem2 = QtWidgets.QSpacerItem(375, 8, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.label_5 = QtWidgets.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.verticalLayout_3.addWidget(self.frame_4)
        self.frame_11 = QtWidgets.QFrame(self.frame_10)
        self.frame_11.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frame_11.setStyleSheet("QFrame {\n"
"    background-color:rgb(232, 232, 232);\n"
"}")
        self.frame_11.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_11)
        self.horizontalLayout_2.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.host = QtWidgets.QLineEdit(self.frame_11)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.host.setFont(font)
        self.host.setStyleSheet("QLineEdit {\n"
"    border-radius:4px;\n"
"    background-color:rgb(232, 232, 232);\n"
"    border:1px solid rgb(132, 132, 132);\n"
"    padding:5px;\n"
"}\n"
"")
        self.host.setObjectName("host")
        self.horizontalLayout_2.addWidget(self.host)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.port = QtWidgets.QSpinBox(self.frame_11)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.port.setFont(font)
        self.port.setStyleSheet("QSpinBox {\n"
"    border-radius:4px;\n"
"    background-color:rgb(232, 232, 232);\n"
"    border:1px solid rgb(132, 132, 132);\n"
"    padding:3px;\n"
"\n"
"}\n"
"\n"
"\n"
"QSpinBox::down-button {\n"
"    width:16;\n"
"    height:14px;\n"
"}\n"
"\n"
"QSpinBox::up-button {\n"
"    width:16;\n"
"    height:14px;\n"
"}\n"
"\n"
"")
        self.port.setFrame(False)
        self.port.setMaximum(9999999)
        self.port.setObjectName("port")
        self.horizontalLayout_2.addWidget(self.port)
        self.horizontalLayout_2.setStretch(0, 2)
        self.horizontalLayout_2.setStretch(2, 1)
        self.verticalLayout_3.addWidget(self.frame_11)
        self.verticalLayout_11.addWidget(self.frame_10)
        self.frame_13 = QtWidgets.QFrame(self.frame_31)
        self.frame_13.setStyleSheet("QFrame {\n"
"    background-color:rgb(232, 232, 232);\n"
"}")
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_13)
        self.verticalLayout_6.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame_14 = QtWidgets.QFrame(self.frame_13)
        self.frame_14.setStyleSheet("QFrame {\n"
"    background-color:rgb(232, 232, 232);\n"
"}")
        self.frame_14.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_14)
        self.verticalLayout_4.setContentsMargins(0, 0, -1, 0)
        self.verticalLayout_4.setSpacing(1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_15 = QtWidgets.QFrame(self.frame_14)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.frame_15.setFont(font)
        self.frame_15.setStyleSheet("QFrame {\n"
"    background-color:rgb(232, 232, 232);\n"
"}")
        self.frame_15.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.frame_15)
        self.horizontalLayout_14.setContentsMargins(9, 0, 132, 2)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_8 = QtWidgets.QLabel(self.frame_15)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("QFrame {\n"
"    background-color:rgb(232, 232, 232);\n"
"}")
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_14.addWidget(self.label_8)
        spacerItem4 = QtWidgets.QSpacerItem(375, 8, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem4)
        self.label_9 = QtWidgets.QLabel(self.frame_15)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_14.addWidget(self.label_9)
        self.verticalLayout_4.addWidget(self.frame_15)
        self.frame_16 = QtWidgets.QFrame(self.frame_14)
        self.frame_16.setStyleSheet("QFrame {\n"
"    background-color:rgb(232, 232, 232);\n"
"}")
        self.frame_16.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.frame_16)
        self.horizontalLayout_15.setContentsMargins(-1, 0, 0, -1)
        self.horizontalLayout_15.setSpacing(1)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.username = QtWidgets.QLineEdit(self.frame_16)
        self.username.setStyleSheet("QLineEdit {\n"
"    border-radius:4px;\n"
"    background-color:rgb(232, 232, 232);\n"
"    border:1px solid rgb(132, 132, 132);\n"
"    padding:5px;\n"
"}\n"
"")
        self.username.setObjectName("username")
        self.horizontalLayout_15.addWidget(self.username)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem5)
        self.password = QtWidgets.QLineEdit(self.frame_16)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.password.setFont(font)
        self.password.setStyleSheet("QLineEdit {\n"
"    border-radius:4px;\n"
"    background-color:rgb(232, 232, 232);\n"
"    border:1px solid rgb(132, 132, 132);\n"
"    padding:5px;\n"
"}\n"
"")
        self.password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password.setPlaceholderText("")
        self.password.setClearButtonEnabled(True)
        self.password.setObjectName("password")
        self.horizontalLayout_15.addWidget(self.password)
        self.showpassword = QtWidgets.QToolButton(self.frame_16)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../images/showpassword.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.showpassword.setIcon(icon)
        self.showpassword.setIconSize(QtCore.QSize(20, 20))
        self.showpassword.setAutoRaise(True)
        self.showpassword.setObjectName("showpassword")
        self.horizontalLayout_15.addWidget(self.showpassword)
        self.horizontalLayout_15.setStretch(0, 1)
        self.horizontalLayout_15.setStretch(2, 1)
        self.verticalLayout_4.addWidget(self.frame_16)
        self.verticalLayout_6.addWidget(self.frame_14)
        self.frame_17 = QtWidgets.QFrame(self.frame_13)
        self.frame_17.setStyleSheet("QFrame {\n"
"    background-color:rgb(232, 232, 232);\n"
"}")
        self.frame_17.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_17)
        self.verticalLayout_5.setContentsMargins(0, 0, -1, 5)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_18 = QtWidgets.QFrame(self.frame_17)
        self.frame_18.setStyleSheet("QFrame {\n"
"    background-color:rgb(232, 232, 232);\n"
"}")
        self.frame_18.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.frame_18)
        self.horizontalLayout_16.setContentsMargins(-1, 0, -1, 2)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_10 = QtWidgets.QLabel(self.frame_18)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("QFrame {\n"
"    background-color:rgb(232, 232, 232);\n"
"}")
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_16.addWidget(self.label_10)
        spacerItem6 = QtWidgets.QSpacerItem(375, 8, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem6)
        self.verticalLayout_5.addWidget(self.frame_18)
        self.frame_19 = QtWidgets.QFrame(self.frame_17)
        self.frame_19.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_19.setObjectName("frame_19")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.frame_19)
        self.horizontalLayout_17.setContentsMargins(-1, 0, 0, 0)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.default_database = QtWidgets.QLineEdit(self.frame_19)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.default_database.setFont(font)
        self.default_database.setStyleSheet("QLineEdit {\n"
"    border-radius:4px;\n"
"    background-color:rgb(232, 232, 232);\n"
"    border:1px solid rgb(132, 132, 132);\n"
"    padding:5px;\n"
"}\n"
"")
        self.default_database.setObjectName("default_database")
        self.horizontalLayout_17.addWidget(self.default_database)
        self.verticalLayout_5.addWidget(self.frame_19)
        self.verticalLayout_6.addWidget(self.frame_17)
        self.frame_20 = QtWidgets.QFrame(self.frame_13)
        self.frame_20.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_20.setObjectName("frame_20")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.frame_20)
        self.horizontalLayout_18.setContentsMargins(9, 3, -1, 5)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.ssh_check = QtWidgets.QCheckBox(self.frame_20)
        self.ssh_check.setStyleSheet("QCheckBox {\n"
"    border:none;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    border-radius:5px;\n"
"    border:2px solid black;\n"
"    width:15px;\n"
"    height:15px;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color:black;\n"
"}\n"
"\n"
"\n"
"QCheckBox::indicator:checked:pressed {\n"
"    image: url(:/images/checked_box.png);\n"
"}\n"
"\n"
"")
        self.ssh_check.setObjectName("ssh_check")
        self.horizontalLayout_18.addWidget(self.ssh_check)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem7)
        self.btn_test = QtWidgets.QPushButton(self.frame_20)
        self.btn_test.setStyleSheet("QPushButton {\n"
"    border-radius:4px;\n"
"    background-color:rgb(175, 175, 175);\n"
"    font: 75 9pt \"Arial\";\n"
"    padding:6px 15px 6px 15px;\n"
"    width:50px;\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"    border-radius:4px;\n"
"    background-color:rgb(145, 145, 145);\n"
"    font: 75 9pt \"Arial\";\n"
"    padding:6px 15px 6px 15px;\n"
"    width:50px;\n"
"}\n"
"\n"
"QPushButton::pressed {\n"
"    border-radius:4px;\n"
"    background-color:rgb(105, 105, 105);\n"
"    font: 70 9pt \"Arial\";\n"
"    padding:6px 15px 6px 15px;\n"
"    width:50px;\n"
"}")
        self.btn_test.setObjectName("btn_test")
        self.horizontalLayout_18.addWidget(self.btn_test)
        self.btn_connect = QtWidgets.QPushButton(self.frame_20)
        self.btn_connect.setStyleSheet("QPushButton {\n"
"    border-radius:4px;\n"
"    background-color:rgb(0, 0, 0);\n"
"    font: 75 9pt \"Arial\";\n"
"    padding:6px 18px 6px 18px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"    border-radius:4px;\n"
"    background-color:rgb(40, 40, 40);\n"
"    font: 75 9pt \"Arial\";\n"
"    padding:6px 18px 6px 18px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border-radius:4px;\n"
"    background-color:rgb(100, 100, 100);\n"
"    font: 75 9pt \"Arial\";\n"
"    padding:6px 18px 6px 18px;\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.btn_connect.setObjectName("btn_connect")
        self.horizontalLayout_18.addWidget(self.btn_connect)
        self.verticalLayout_6.addWidget(self.frame_20)
        self.verticalLayout_11.addWidget(self.frame_13)
        self.ssh_frame = QtWidgets.QFrame(self.frame_31)
        self.ssh_frame.setEnabled(True)
        self.ssh_frame.setStyleSheet("QFrame {\n"
"    background-color:rgb(232, 232, 232);\n"
"}")
        self.ssh_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.ssh_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ssh_frame.setObjectName("ssh_frame")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.ssh_frame)
        self.verticalLayout_10.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.frame_25 = QtWidgets.QFrame(self.ssh_frame)
        self.frame_25.setStyleSheet("QFrame {\n"
"    background-color:rgb(232, 232, 232);\n"
"}")
        self.frame_25.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_25.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_25.setObjectName("frame_25")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_25)
        self.verticalLayout_8.setContentsMargins(0, 0, -1, 0)
        self.verticalLayout_8.setSpacing(1)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.frame_26 = QtWidgets.QFrame(self.frame_25)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.frame_26.setFont(font)
        self.frame_26.setStyleSheet("QFrame {\n"
"    background-color:rgb(232, 232, 232);\n"
"}")
        self.frame_26.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_26.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_26.setObjectName("frame_26")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout(self.frame_26)
        self.horizontalLayout_21.setContentsMargins(9, 0, 116, 0)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.label_13 = QtWidgets.QLabel(self.frame_26)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("QFrame {\n"
"    background-color:rgb(232, 232, 232);\n"
"}")
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_21.addWidget(self.label_13)
        spacerItem8 = QtWidgets.QSpacerItem(375, 8, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem8)
        self.label_14 = QtWidgets.QLabel(self.frame_26)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_21.addWidget(self.label_14)
        self.verticalLayout_8.addWidget(self.frame_26)
        self.frame_27 = QtWidgets.QFrame(self.frame_25)
        self.frame_27.setStyleSheet("QFrame {\n"
"    background-color:rgb(232, 232, 232);\n"
"}")
        self.frame_27.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_27.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_27.setObjectName("frame_27")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout(self.frame_27)
        self.horizontalLayout_22.setContentsMargins(-1, 0, 0, -1)
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.ssh_hostname = QtWidgets.QLineEdit(self.frame_27)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ssh_hostname.setFont(font)
        self.ssh_hostname.setStyleSheet("QLineEdit {\n"
"    border-radius:4px;\n"
"    background-color:rgb(232, 232, 232);\n"
"    border:1px solid rgb(132, 132, 132);\n"
"    padding:5px;\n"
"}\n"
"")
        self.ssh_hostname.setObjectName("ssh_hostname")
        self.horizontalLayout_22.addWidget(self.ssh_hostname)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem9)
        self.ssh_port = QtWidgets.QSpinBox(self.frame_27)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ssh_port.setFont(font)
        self.ssh_port.setStyleSheet("QSpinBox {\n"
"    border-radius:4px;\n"
"    background-color:rgb(232, 232, 232);\n"
"    border:1px solid rgb(132, 132, 132);\n"
"    padding:3px;\n"
"\n"
"}\n"
"\n"
"\n"
"QSpinBox::down-button {\n"
"    width:16;\n"
"    height:14px;\n"
"}\n"
"\n"
"QSpinBox::up-button {\n"
"    width:16;\n"
"    height:14px;\n"
"}\n"
"\n"
"")
        self.ssh_port.setFrame(False)
        self.ssh_port.setMaximum(99999)
        self.ssh_port.setObjectName("ssh_port")
        self.horizontalLayout_22.addWidget(self.ssh_port)
        self.horizontalLayout_22.setStretch(0, 2)
        self.horizontalLayout_22.setStretch(2, 1)
        self.verticalLayout_8.addWidget(self.frame_27)
        self.verticalLayout_10.addWidget(self.frame_25)
        self.frame_28 = QtWidgets.QFrame(self.ssh_frame)
        self.frame_28.setStyleSheet("QFrame {\n"
"    background-color:rgb(232, 232, 232);\n"
"}")
        self.frame_28.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_28.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_28.setObjectName("frame_28")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_28)
        self.verticalLayout_9.setContentsMargins(0, 0, -1, 0)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.frame_29 = QtWidgets.QFrame(self.frame_28)
        self.frame_29.setStyleSheet("QFrame {\n"
"    background-color:rgb(232, 232, 232);\n"
"}")
        self.frame_29.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_29.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_29.setObjectName("frame_29")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout(self.frame_29)
        self.horizontalLayout_23.setContentsMargins(-1, 0, -1, 2)
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.label_15 = QtWidgets.QLabel(self.frame_29)
        self.label_15.setStyleSheet("QFrame {\n"
"    background-color:rgb(232, 232, 232);\n"
"}")
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_23.addWidget(self.label_15)
        spacerItem10 = QtWidgets.QSpacerItem(375, 8, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem10)
        self.verticalLayout_9.addWidget(self.frame_29)
        self.frame_30 = QtWidgets.QFrame(self.frame_28)
        self.frame_30.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_30.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_30.setLineWidth(0)
        self.frame_30.setObjectName("frame_30")
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout(self.frame_30)
        self.horizontalLayout_24.setContentsMargins(-1, 0, 0, 0)
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.ssh_authentication = QtWidgets.QComboBox(self.frame_30)
        self.ssh_authentication.setStyleSheet("QComboBox {\n"
"    border-radius:4px;\n"
"    background-color:rgb(232, 232, 232);\n"
"    border:1px solid rgb(132, 132, 132);\n"
"    padding:5px;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    padding:6px;\n"
"    color: rgb(95, 95, 95);\n"
"    border:1px solid  rgb(159, 159, 159);\n"
"}")
        self.ssh_authentication.setObjectName("ssh_authentication")
        self.ssh_authentication.addItem("")
        self.horizontalLayout_24.addWidget(self.ssh_authentication)
        self.verticalLayout_9.addWidget(self.frame_30)
        self.verticalLayout_10.addWidget(self.frame_28)
        self.frame_22 = QtWidgets.QFrame(self.ssh_frame)
        self.frame_22.setStyleSheet("QFrame {\n"
"    background-color:rgb(232, 232, 232);\n"
"}")
        self.frame_22.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_22.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_22.setObjectName("frame_22")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_22)
        self.verticalLayout_7.setContentsMargins(0, 0, -1, 0)
        self.verticalLayout_7.setSpacing(1)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.frame_23 = QtWidgets.QFrame(self.frame_22)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.frame_23.setFont(font)
        self.frame_23.setStyleSheet("QFrame {\n"
"    background-color:rgb(232, 232, 232);\n"
"}")
        self.frame_23.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_23.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_23.setObjectName("frame_23")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.frame_23)
        self.horizontalLayout_19.setContentsMargins(9, 0, 132, 0)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_11 = QtWidgets.QLabel(self.frame_23)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("QFrame {\n"
"    background-color:rgb(232, 232, 232);\n"
"}")
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_19.addWidget(self.label_11)
        spacerItem11 = QtWidgets.QSpacerItem(375, 8, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem11)
        self.label_12 = QtWidgets.QLabel(self.frame_23)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_19.addWidget(self.label_12)
        self.verticalLayout_7.addWidget(self.frame_23)
        self.frame_24 = QtWidgets.QFrame(self.frame_22)
        self.frame_24.setStyleSheet("QFrame {\n"
"    background-color:rgb(232, 232, 232);\n"
"}")
        self.frame_24.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_24.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_24.setObjectName("frame_24")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout(self.frame_24)
        self.horizontalLayout_20.setContentsMargins(-1, 0, 0, 0)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.ssh_username = QtWidgets.QLineEdit(self.frame_24)
        self.ssh_username.setStyleSheet("QLineEdit {\n"
"    border-radius:4px;\n"
"    background-color:rgb(232, 232, 232);\n"
"    border:1px solid rgb(132, 132, 132);\n"
"    padding:5px;\n"
"}\n"
"")
        self.ssh_username.setObjectName("ssh_username")
        self.horizontalLayout_20.addWidget(self.ssh_username)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem12)
        self.ssh_password = QtWidgets.QLineEdit(self.frame_24)
        self.ssh_password.setStyleSheet("QLineEdit {\n"
"    border-radius:4px;\n"
"    background-color:rgb(232, 232, 232);\n"
"    border:1px solid rgb(132, 132, 132);\n"
"    padding:5px;\n"
"}\n"
"")
        self.ssh_password.setObjectName("ssh_password")
        self.horizontalLayout_20.addWidget(self.ssh_password)
        self.horizontalLayout_20.setStretch(0, 1)
        self.horizontalLayout_20.setStretch(2, 1)
        self.verticalLayout_7.addWidget(self.frame_24)
        self.verticalLayout_10.addWidget(self.frame_22)
        self.verticalLayout_11.addWidget(self.ssh_frame)
        self.frame_2 = QtWidgets.QFrame(self.frame_31)
        self.frame_2.setStyleSheet("QFrame {\n"
"    background-color:rgb(232, 232, 232);\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout.setContentsMargins(-1, 0, -1, 6)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_6 = QtWidgets.QFrame(self.frame_2)
        self.frame_6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_10.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_7 = QtWidgets.QLabel(self.frame_6)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_10.addWidget(self.label_7)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem13)
        self.verticalLayout.addWidget(self.frame_6)
        self.frame_7 = QtWidgets.QFrame(self.frame_2)
        self.frame_7.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_12.setContentsMargins(-1, 0, -1, 5)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.connection_save_name = QtWidgets.QLineEdit(self.frame_7)
        self.connection_save_name.setStyleSheet("QLineEdit {\n"
"    border-radius:4px;\n"
"    background-color:rgb(232, 232, 232);\n"
"    border:1px solid rgb(132, 132, 132);\n"
"    padding:5px;\n"
"}\n"
"")
        self.connection_save_name.setObjectName("connection_save_name")
        self.horizontalLayout_12.addWidget(self.connection_save_name)
        self.verticalLayout.addWidget(self.frame_7)
        self.frame_8 = QtWidgets.QFrame(self.frame_2)
        self.frame_8.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_9.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.save_passwords = QtWidgets.QCheckBox(self.frame_8)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.save_passwords.setFont(font)
        self.save_passwords.setStyleSheet("QCheckBox {\n"
"    border:none;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    border-radius:5px;\n"
"    border:2px solid black;\n"
"    width:15px;\n"
"    height:15px;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color:black;\n"
"}\n"
"\n"
"\n"
"QCheckBox::indicator:checked:pressed {\n"
"    image: url(:/images/checked_box.png);\n"
"}\n"
"\n"
"")
        self.save_passwords.setObjectName("save_passwords")
        self.horizontalLayout_9.addWidget(self.save_passwords)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem14)
        self.verticalLayout.addWidget(self.frame_8)
        self.frame_9 = QtWidgets.QFrame(self.frame_2)
        self.frame_9.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frame_9)
        self.horizontalLayout_11.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem15)
        self.btn_save_connection = QtWidgets.QPushButton(self.frame_9)
        self.btn_save_connection.setStyleSheet("QPushButton {\n"
"    border-radius:4px;\n"
"    background-color:rgb(175, 175, 175);\n"
"    font: 75 9pt \"Arial\";\n"
"    padding:6px 15px 6px 15px;\n"
"    width:50px;\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"    border-radius:4px;\n"
"    background-color:rgb(145, 145, 145);\n"
"    font: 75 9pt \"Arial\";\n"
"    padding:6px 15px 6px 15px;\n"
"    width:50px;\n"
"}\n"
"\n"
"QPushButton::pressed {\n"
"    border-radius:4px;\n"
"    background-color:rgb(105, 105, 105);\n"
"    font: 70 9pt \"Arial\";\n"
"    padding:6px 15px 6px 15px;\n"
"    width:50px;\n"
"}")
        self.btn_save_connection.setObjectName("btn_save_connection")
        self.horizontalLayout_11.addWidget(self.btn_save_connection)
        self.verticalLayout.addWidget(self.frame_9)
        self.verticalLayout_11.addWidget(self.frame_2)
        self.verticalLayout_12.addWidget(self.frame_31)

        self.retranslateUi(Dialog)
        self.ssh_check.toggled['bool'].connect(self.ssh_frame.setVisible) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "MySQL"))
        self.label.setText(_translate("Dialog", "New Connection"))
        self.connection_name.setText(_translate("Dialog", "MySQL"))
        self.label_3.setText(_translate("Dialog", "Connection Mode"))
        self.connection_type.setItemText(0, _translate("Dialog", "Host and Port"))
        self.label_4.setText(_translate("Dialog", "Host"))
        self.label_5.setText(_translate("Dialog", "Port"))
        self.label_8.setText(_translate("Dialog", "UserName"))
        self.label_9.setText(_translate("Dialog", "Password"))
        self.showpassword.setText(_translate("Dialog", "..."))
        self.label_10.setText(_translate("Dialog", "Default Database"))
        self.ssh_check.setText(_translate("Dialog", " SSH Tunnel"))
        self.btn_test.setText(_translate("Dialog", "Test"))
        self.btn_connect.setText(_translate("Dialog", "Connect"))
        self.label_13.setText(_translate("Dialog", "SSH Hostname"))
        self.label_14.setText(_translate("Dialog", "Port"))
        self.label_15.setText(_translate("Dialog", "SSH Authentication"))
        self.ssh_authentication.setItemText(0, _translate("Dialog", "Username & Password"))
        self.label_11.setText(_translate("Dialog", "UserName"))
        self.label_12.setText(_translate("Dialog", "Password"))
        self.label_7.setText(_translate("Dialog", "Save Connection"))
        self.connection_save_name.setPlaceholderText(_translate("Dialog", "Connection Name"))
        self.save_passwords.setText(_translate("Dialog", "Save Passwords"))
        self.btn_save_connection.setText(_translate("Dialog", "Save"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
