# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sqlitecon.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(485, 375)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_5 = QtWidgets.QFrame(Dialog)
        self.frame_5.setStyleSheet("QFrame {\n"
"    background-color:rgb(232, 232, 232);\n"
"}")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout.setContentsMargins(-1, 3, -1, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.frame_5)
        self.frame.setStyleSheet("QFrame {\n"
"    background-color:rgb(232, 232, 232);\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButton = QtWidgets.QPushButton(self.frame)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton {\n"
"    text-align:right;\n"
"}")
        self.pushButton.setFlat(True)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.verticalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.frame_5)
        self.frame_2.setStyleSheet("QFrame {\n"
"    background-color:rgb(232, 232, 232);\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setStyleSheet("QFrame {\n"
"    background-color:rgb(232, 232, 232);\n"
"}")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        spacerItem1 = QtWidgets.QSpacerItem(375, 8, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.frame_5)
        self.frame_3.setStyleSheet("QFrame {\n"
"    background-color:rgb(232, 232, 232);\n"
"}")
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.sqlitefilename = QtWidgets.QLineEdit(self.frame_3)
        self.sqlitefilename.setStyleSheet("QLineEdit {\n"
"    border-top-left-radius:4px;\n"
"    border-bottom-left-radius:4px;\n"
"    background-color:rgb(232, 232, 232);\n"
"    border:1px solid rgb(132, 132, 132);\n"
"    padding:5px;\n"
"    height:17px;\n"
"}\n"
"")
        self.sqlitefilename.setObjectName("sqlitefilename")
        self.horizontalLayout_3.addWidget(self.sqlitefilename)
        self.btn_filechooser = QtWidgets.QPushButton(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_filechooser.sizePolicy().hasHeightForWidth())
        self.btn_filechooser.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.btn_filechooser.setFont(font)
        self.btn_filechooser.setStyleSheet("QPushButton {\n"
"    border-top-right-radius:4px;\n"
"    border-bottom-right-radius:4px;\n"
"    background-color:rgb(175, 175, 175);\n"
"    font: 75 9pt \"Arial\";\n"
"    padding:8px;\n"
"    height:13px;\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"    border-top-right-radius:4px;\n"
"    border-bottom-right-radius:4px;\n"
"    background-color:rgb(155, 155, 155);\n"
"    font: 75 9pt \"Arial\";\n"
"    padding:8px;\n"
"    height:13px;\n"
"}\n"
"\n"
"QPushButton::pressed {\n"
"    border-top-right-radius:4px;\n"
"    border-bottom-right-radius:4px;\n"
"    background-color:rgb(115, 115, 115);\n"
"    font: 75 9pt \"Arial\";\n"
"    padding:8px;\n"
"    height:13px;\n"
"}")
        self.btn_filechooser.setObjectName("btn_filechooser")
        self.horizontalLayout_3.addWidget(self.btn_filechooser)
        self.verticalLayout.addWidget(self.frame_3)
        self.frame_4 = QtWidgets.QFrame(self.frame_5)
        self.frame_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.btn_test_con = QtWidgets.QPushButton(self.frame_4)
        self.btn_test_con.setStyleSheet("QPushButton {\n"
"    border-radius:4px;\n"
"    background-color:rgb(175, 175, 175);\n"
"    font: 75 9pt \"Arial\";\n"
"    padding:6px 15px 6px 15px;\n"
"    width:50px;\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"    border-radius:4px;\n"
"    background-color:rgb(155, 155, 155);\n"
"    font: 75 9pt \"Arial\";\n"
"    padding:6px 15px 6px 15px;\n"
"    width:50px;\n"
"}\n"
"\n"
"QPushButton::pressed {\n"
"    border-radius:4px;\n"
"    background-color:rgb(115, 115, 115);\n"
"    font: 75 9pt \"Arial\";\n"
"    padding:6px 15px 6px 15px;\n"
"    width:50px;\n"
"}")
        self.btn_test_con.setObjectName("btn_test_con")
        self.horizontalLayout_4.addWidget(self.btn_test_con)
        self.btn_connect = QtWidgets.QPushButton(self.frame_4)
        self.btn_connect.setStyleSheet("QPushButton {\n"
"    border-radius:4px;\n"
"    background-color:rgb(0, 0, 0);\n"
"    font: 75 9pt \"Arial\";\n"
"    padding:6px 18px 6px 18px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"    border-radius:4px;\n"
"    background-color:rgb(40, 40, 40);\n"
"    font: 75 9pt \"Arial\";\n"
"    padding:6px 18px 6px 18px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border-radius:4px;\n"
"    background-color:rgb(100, 100, 100);\n"
"    font: 75 9pt \"Arial\";\n"
"    padding:6px 18px 6px 18px;\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.btn_connect.setObjectName("btn_connect")
        self.horizontalLayout_4.addWidget(self.btn_connect)
        self.verticalLayout.addWidget(self.frame_4)
        self.line = QtWidgets.QFrame(self.frame_5)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.frame_6 = QtWidgets.QFrame(self.frame_5)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_3 = QtWidgets.QLabel(self.frame_6)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_5.addWidget(self.label_3)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.verticalLayout.addWidget(self.frame_6)
        self.frame_7 = QtWidgets.QFrame(self.frame_5)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.connection_sqlite_name = QtWidgets.QLineEdit(self.frame_7)
        self.connection_sqlite_name.setStyleSheet("QLineEdit {\n"
"    border-radius:4px;\n"
"    background-color:rgb(232, 232, 232);\n"
"    border:1px solid rgb(132, 132, 132);\n"
"    padding:5px;\n"
"}\n"
"")
        self.connection_sqlite_name.setObjectName("connection_sqlite_name")
        self.horizontalLayout_6.addWidget(self.connection_sqlite_name)
        self.verticalLayout.addWidget(self.frame_7)
        self.frame_8 = QtWidgets.QFrame(self.frame_5)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.save_password = QtWidgets.QCheckBox(self.frame_8)
        self.save_password.setStyleSheet("QCheckBox {\n"
"    border:none;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    border-radius:5px;\n"
"    border:2px solid black;\n"
"    width:15px;\n"
"    height:15px;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color:black;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked:pressed {\n"
"    image: url(:/images/checked_box.png);\n"
"}\n"
"\n"
"\n"
"")
        self.save_password.setObjectName("save_password")
        self.horizontalLayout_7.addWidget(self.save_password)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem4)
        self.verticalLayout.addWidget(self.frame_8)
        self.frame_9 = QtWidgets.QFrame(self.frame_5)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_9)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem5)
        self.btn_save_connection = QtWidgets.QPushButton(self.frame_9)
        self.btn_save_connection.setStyleSheet("QPushButton {\n"
"    border-radius:4px;\n"
"    background-color:rgb(175, 175, 175);\n"
"    font: 75 9pt \"Arial\";\n"
"    padding:6px 15px 6px 15px;\n"
"    width:50px;\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"    border-radius:4px;\n"
"    background-color:rgb(155, 155, 155);\n"
"    font: 75 9pt \"Arial\";\n"
"    padding:6px 15px 6px 15px;\n"
"    width:50px;\n"
"}\n"
"\n"
"QPushButton::pressed {\n"
"    border-radius:4px;\n"
"    background-color:rgb(115, 115, 115);\n"
"    font: 75 9pt \"Arial\";\n"
"    padding:6px 15px 6px 15px;\n"
"    width:50px;\n"
"}")
        self.btn_save_connection.setObjectName("btn_save_connection")
        self.horizontalLayout_8.addWidget(self.btn_save_connection)
        self.verticalLayout.addWidget(self.frame_9)
        self.verticalLayout_2.addWidget(self.frame_5)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "sqliteconnection"))
        self.label.setText(_translate("Dialog", "New Connection"))
        self.pushButton.setText(_translate("Dialog", "SQLite"))
        self.label_2.setText(_translate("Dialog", "DataBase File"))
        self.sqlitefilename.setPlaceholderText(_translate("Dialog", "Nothing Selected"))
        self.btn_filechooser.setText(_translate("Dialog", "Choose File"))
        self.btn_test_con.setText(_translate("Dialog", "Test"))
        self.btn_connect.setText(_translate("Dialog", "Connect"))
        self.label_3.setText(_translate("Dialog", "Save Connection"))
        self.connection_sqlite_name.setPlaceholderText(_translate("Dialog", "Connection Name"))
        self.save_password.setText(_translate("Dialog", "Save Passwords"))
        self.btn_save_connection.setText(_translate("Dialog", "Save"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
